#ifndef FixLog_h
#define FixLog_h 1

//Color設定
#define Th1Color		RGB(203,  0,  0)	//RED
#define Th2Color		RGB(  0, 63,255)	//BULE
#define Th3Color		RGB(  0,203,  0)	//GREEN
#define Th4Color		RGB(150,245,100)	//LIME_GREEN
#define Th5Color		RGB(255,  0,191)	//PINK
#define Ctl1Color		RGB(  0,255,191)	//MINT
#define Ctl0Color		RGB( 50,204,255)	//LTBLUE
#define InfoColor		RGB(255,  0,  0)	//RED
#define DutyColor		RGB(  0,255,  0)	//LTGREEN
#define DutySubColor	RGB(255,204,153)	//肌色
#define StateColor		RGB(203,101,  0)	//BROWN
#define HTRMainColor	RGB(255,127,  0)	//ORANGE
#define HTRSubColor		RGB(255, 63,  0)	//ORANGE
#define PressColor		RGB(255,255,  0)	//YELLOW
#define IhCoreColor		RGB(  0,  0,255)	//BULE

enum eTOOLBAR_MENU {
	ECOMMAND_SCALEUP = 1,	//拡大
	ECOMMAND_SCALEDOWN,		//縮小
	ECOMMAND_HELP,			//ヘルプ（凡例）
	ECOMMAND_FIXINSERT,		//Fix入力
	ECOMMAND_DISPALL,		//全体表示ボタン
	ECOMMAND_SAVE,			//保存
	ECOMMAND_TIMEWIDTH,		//時間の幅
	ECOMMAND_MOVE,			//カーソル移動
	ECOMMAND_YDATA,			//温度,値
	ECOMMAND_CLOSE_YDATA,	//近くの値表示
	ECOMMAND_VERTICAL,		//横線ボタン
	ECOMMAND_HORIZONAL,		//縦線ボタン
	ECOMMAND_RESET,			//Resetボタン
	ECOMMAND_ALLRESET		//白紙ボタン
};

enum eANALYZ_STATE {
	EANALYZ_NORMAL,					//マウスは通常状態
	EANALYZ_WATCH_YDATA,			//温度計ボタン
	EANALYZ_WATCH_YDATA_LINE,		//温度計ボタン2
	EANALYZ_VERTICAL,				//横線ボタン
	EANALYZ_HORIZONAL,				//縦線ボタン
	EANALYZ_TIME_WIDTH,				//時間計測ボタン
	EANALYZ_TIME_WIDTH_LINE,		//時間計測ボタン2
	EANALYZ_ALL_PAINT				//全体表示ボタン（すべて描画中状態）				
};

enum eANALYZ_LOG_STATE {
	EANALYZ_IDLE,
	EANALYZ_DROP_FILE,
	EANALYZ_SELECT_RANGE,
	EANALYZ_FILE_RELOAD
};

enum eANALYZ_CLICK_STATE {
	EANALYZ_MOUSE_DOWN,
	EANALYZ_MOUSE_MOVE,
	EANALYZ_MOUSE_UP
};

enum eANALYZ_LOG_TYPE {
	EANALYZ_LOG_TH1,
	EANALYZ_LOG_TH2,
	EANALYZ_LOG_TH3,
	EANALYZ_LOG_TH4,
	EANALYZ_LOG_TH5,
	EANALYZ_LOG_CTL0,
	EANALYZ_LOG_CTL1,
	EANALYZ_LOG_INFO,
	EANALYZ_LOG_DUTY,
	EANALYZ_LOG_DUTYSUB,
	EANALYZ_LOG_STATE,
	EANALYZ_LOG_HTRMAIN,
	EANALYZ_LOG_HTRSUB,
	EANALYZ_LOG_PRESS,
	EANALYZ_LOG_IHCORE,

	EANALYZ_LOG_NUM
};

enum eANALYZ_TOOL {
	EANALYZ_TOOL_YDATA,
	EANALYZ_TOOL_TIMEWIDTH,
	EANALYZ_TOOL_HORIZONAL,
	EANALYZ_TOOL_VERTICAL,

	EANALYZ_TOOL_NUM
};

enum eANALYZ_PRINT_PROFILE {
	EANALYZ_PASIZE,
	EANALYZ_MEDIATYPE,
	EANALYZ_COLORMODE,
	EANALYZ_PAWEIGHT,
	EANALYZ_PASPEED,
	EANALYZ_PAFEED,
	EANALYZ_PASIDE,
	EANALYZ_ANYLOG,

	EANALYZ_PRINT_PROFILE_NUM
};
#endif



