#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_TOOLBAR1                            101
#define IDR_TOOLBAR2                            102
#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDR_TOOLBAR3                            105
#define IDI_SMALL                               108
#define IDC_LOGTOOL                             109
#define IDD_DIALOG_SETTING                      113
#define IDD_DIALOG_SYSLOG                       114
#define IDI_LOGTOOL                             116
#define IDR_MENU1                               118
#define IDR_ANALYZER                            120
#define IDD_DIALOG_DL                           123
#define IDD_COM_SETTING                         125
#define IDD_DL_PASSWORD                         129
#define IDR_MENU2                               130
#define IDR_MENU3                               131
#define IDD_AUTO_COMMAND_SEND                   132
#define IDD_WAIT_SETTINT                        133
#define IDD_DISP_SETTING                        134
#define IDD_STRING_SEARCH                       136
#define IDD_TCM_SETTING                         138
#define IDD_USE_COUNT                           141
#define IDR_MENU4                               142
#define IDD_VISUAL_ANALYZER_LINE                144
#define IDD_VISUAL_ANALYZER_DEVICE              145
#define IDD_VISUAL_ANALYZER_OPERATION           150
#define IDD_VISUAL_ANALYZER_START_PART          153
#define IDD_VISUAL_ANALYZER_TEST_MODE           155
#define IDD_VISUAL_ANALYZER_BY_PATTERN          157
#define IDC_EDIT_LOGMES_FILE                    40000
#define IDC_MSG_VERSION                         40000
#define IDM_ADD_POS                             40000
#define IDM_ANALYS_LEGEND                       40000
#define IDM_DISP_SYSLOG                         40000
#define IDR_COMMAND3                            40000
#define IDSAVE                                  40000
#define IDS_TIMEOUT                             40000
#define ID_BOOT                                 40000
#define ID_EXECUTE                              40000
#define ID_FILTER                               40000
#define ID_NEW_POINT                            40000
#define ID_PASS_WORD                            40000
#define ID_PORT                                 40000
#define ID_ROLLER1                              40000
#define ID_STRING                               40000
#define ID_TEXT_CALCULATION                     40000
#define ID_TEXT_SIZE                            40000
#define ID_USE_COUNT_URL                        40000
#define ID_VA_INI_NAME                          40000
#define IDC_EDIT_SYSLOG_FIL                     40001
#define IDC_STATIC2                             40001
#define IDC_SYSLOG                              40001
#define IDM_CREATE_TCMLOG                       40001
#define IDM_DISP_BOX_TH1                        40001
#define IDM_OPERATION_SETTING                   40001
#define IDR_COMMAND4                            40001
#define IDS_PASS_TIME                           40001
#define IDS_TIMEOUT_COMB                        40001
#define ID_COMB2                                40001
#define ID_DISTANCE                             40001
#define ID_ERASE                                40001
#define ID_FORMULA                              40001
#define ID_SEARCH_UP                            40001
#define ID_SIZE                                 40001
#define ID_STOP                                 40001
#define ID_TEST_SEND                            40001
#define ID_VA_READ_FILE                         40001
#define IDC_PROGRESS                            40002
#define IDC_STATIC3                             40002
#define IDFSEL1                                 40002
#define IDM_DISP_BOX_TH2                        40002
#define IDM_EXIT                                40002
#define IDREFLESH                               40002
#define IDR_COMMAND5                            40002
#define IDS_MSEC                                40002
#define IDS_TIMEOUT_BRANCH                      40002
#define ID_ADD_POINT                            40002
#define ID_DISTANCE_VALUE                       40002
#define ID_PAT_CLEAR                            40002
#define ID_PAUSE                                40002
#define ID_SENSOR                               40002
#define ID_TEXT1                                40002
#define ID_TEXT_STEP_CTRL                       40002
#define IDFSEL2                                 40003
#define IDM_DEVICE                              40003
#define IDM_DISP_BOX_TH3                        40003
#define IDM_SETTING                             40003
#define IDR_COMMAND6                            40003
#define IDS_DETECT_ENG_LOG                      40003
#define IDTCMSAVE                               40003
#define ID_CLEAR                                40003
#define ID_CONNECT_POINT                        40003
#define ID_DISP_MSG                             40003
#define ID_NAME                                 40003
#define ID_SEARCH_DOWN                          40003
#define ID_TEXT2                                40003
#define ID_TEXT_PAGEID                          40003
#define ID_TEXT_STEP                            40003
#define IDM_DISP_BOX_TH5                        40004
#define IDR_COMMAND7                            40004
#define IDS_REG_CHECK                           40004
#define ID_ADAPT                                40004
#define ID_ROLLER2                              40004
#define ID_STEP_NUM                             40004
#define ID_TEXT3                                40004
#define LABEL_STATIC                            40004
#define OVERWRITE_SAVE                          40004
#define IDC_SELGRP                              40005
#define IDM_DISP_BOX_CTL0                       40005
#define IDR_COMMAND8                            40005
#define IDS_TEXT7                               40005
#define ID_EDIT_POINT                           40005
#define ID_FILE_READ                            40005
#define ID_PAGE_ID                              40005
#define ID_SCE_PARAM                            40005
#define ID_SEND_DELAY                           40005
#define ID_SOLENOID                             40005
#define ID_STEP_TIME                            40005
#define IDALLGRPSEL                             40006
#define IDM_DISP_BOX_CTL1                       40006
#define IDM_START_POINT                         40006
#define IDR_COMMAND9                            40006
#define IDS_DETECT_LOG_BRANCH                   40006
#define ID_BINARY                               40006
#define ID_BRANCH                               40006
#define ID_DRIVE_TYPE                           40006
#define ID_FILTER_TEXT_1                        40006
#define ID_TEXT_START_SETTING                   40006
#define ID_TEXT_STEP_TIME                       40006
#define OTHER_NAME_SAVE                         40006
#define IDM_DISP_BOX_INFO                       40007
#define IDR_COMMAND10                           40007
#define IDS_TEXT1                               40007
#define ID_ADDTION                              40007
#define ID_ASCII                                40007
#define ID_EDIT_CONDITION                       40007
#define ID_GRP_ERR                              40007
#define ID_LOG_DISP                             40007
#define ID_START_PART_LIST                      40007
#define GROUP_STATIC                            40008
#define IDM_DISP_BOX_DUTY                       40008
#define IDR_COMMAND11                           40008
#define IDS_TEXT2                               40008
#define ID_DELETE                               40008
#define ID_INFOMATION                           40008
#define ID_TEXT4                                40008
#define ID_TEXT_SELECT                          40008
#define IDM_BY_PATTERN                          40009
#define IDM_DISP_BOX_DUTYSUB                    40009
#define IDR_COMMAND12                           40009
#define IDS_TEXT3                               40009
#define ID_FILTER_TEXT_2                        40009
#define ID_GRP_WARN                             40009
#define ID_LENGTH                               40009
#define ID_OPEN_STC                             40009
#define ID_TEXT5                                40009
#define ID_TEXT_NAME                            40009
#define IDM_DISP_BOX_STATE                      40010
#define IDM_TEST_MODE                           40010
#define IDS_TEXT4                               40010
#define ID_COMB1                                40010
#define ID_GROUPING                             40010
#define ID_GRP_INFO                             40010
#define ID_SIZE_MM                              40010
#define ID_TEXT_OPERATION                       40010
#define IDM_DISP_BOX_HTRMAIN                    40011
#define IDSEND                                  40011
#define IDS_TEXT5                               40011
#define ID_BAUD_RATE                            40011
#define ID_EDIT                                 40011
#define ID_MOVE_UP                              40011
#define ID_SWITCH_BACK                          40011
#define ID_TEXT_CONDITION                       40011
#define ID_VA_OTHER_NAME_SAVE                   40011
#define IDM_DISP_BOX_HTRSUB                     40012
#define IDS_TEXT6                               40012
#define ID_MOVE_DOWN                            40012
#define ID_OPE_DEV                              40012
#define ID_SPLIT                                40012
#define ID_TEXT6                                40012
#define ID_VA_FILE_READ                         40012
#define IDM_DISP_BOX_PRESS                      40013
#define IDS_CLEAR                               40013
#define ID_CHECK                                40013
#define ID_DRIVE_SOURCE                         40013
#define ID_HIDE_NUMBERS                         40013
#define ID_OPE_VALUE                            40013
#define ID_TEXT7                                40013
#define IDA_RES_COMMENT_DISP                    40014
#define IDC_SEND_TEXT                           40014
#define IDM_DISP_BOX_IHCORE                     40014
#define ID_OPE_DIR                              40014
#define ID_TEXT8                                40014
#define ID_TEXT_DEV                             40014
#define IDM_CHOICE_BOX_TH1                      40015
#define IDM_DISP_VERINFO                        40015
#define ID_ADD_CONDITION                        40015
#define ID_TEST_LOG_SEND                        40015
#define IDM_CHOICE_BOX_TH2                      40016
#define IDM_LOG_END                             40016
#define ID_EXAMPLE                              40016
#define ID_TEST_ID                              40016
#define IDM_CHOICE_BOX_TH3                      40017
#define IDM_SAVE_LOGBIN                         40017
#define ID_OPE_SELECT                           40017
#define ID_TEXT_VALUE                           40017
#define IDM_CHOICE_BOX_TH5                      40018
#define ID_OPE_NAME                             40018
#define ID_TEXT_GROUP                           40018
#define IDM_CHECK_BOX                           40019
#define IDM_CHOICE_BOX_CTL0                     40019
#define ID_OPE_DEV1                             40019
#define ID_TEXT_ID                              40019
#define IDM_CHOICE_BOX_CTL1                     40020
#define IDM_DISP_FIXLOG                         40020
#define ID_OPE_DEV2                             40020
#define ID_TEST_NAME                            40020
#define IDM_CHOICE_BOX_INFO                     40021
#define IDM_DOWNLOAD                            40021
#define IDR_COMMAND1                            40021
#define ID_CONDITION1                           40021
#define ID_TEST_VALUE                           40021
#define IDM_CHOICE_BOX_DUTY                     40022
#define IDM_COM_SETTING                         40022
#define IDR_COMMAND2                            40022
#define ID_CONDITION2                           40022
#define ID_VIEW                                 40022
#define IDM_CHOICE_BOX_DUTYSUB                  40023
#define IDM_DISP_SETTING                        40023
#define ID_SIGNAL                               40023
#define ID_TEXT_OPE_DEV                         40023
#define IDM_CHOICE_BOX_STATE                    40024
#define IDM_VISUAL_ANALYZER                     40024
#define ID_NONE_DEVICE                          40024
#define ID_TEXT_OPE_VAL                         40024
#define IDM_CHOICE_BOX_HTRMAIN                  40025
#define ID_TEXT_OPE_DIR                         40025
#define IDM_CHOICE_BOX_HTRSUB                   40026
#define IDM_CHOICE_BOX_PRESS                    40027
#define IDM_CHOICE_BOX_IHCORE                   40028
#define IDM_COMMAND_SENDER                      40028
#define IDM_CHECK_TIME_STAMP                    40029
#define IDM_DISP_BOX_TH4                        40029
#define IDM_CHOICE_BOX_TH4                      40030
#define IDM_LOGUPDATE_ALWAYS                    40030
#define IDM_LOGUPDATE_TIMER                     40031
#define IDM_TIMING_CHART                        40032
#define ID_HIDDEN                               40032
#define ID_AUTO_START                           40033
#define ID_TEXT_PARAM                           40034
#define IDM_MACRO_START                         40035
#define IDM_MACRO_STOP                          40036
#define ID_OPEN_TEXT_APP                        40037
#define IDM_DATA_SETTING                        40038
