#ifndef TimingChart_h
#define TimingChart_h 1


#define TCM_TIMER_ID 1

enum eTCM_TOOLBAR_MENU {
	ECOMMAND_TCM_SCALEUP = 1,	//拡大
	ECOMMAND_TCM_SCALEDOWN,		//縮小
	ECOMMAND_TCM_TCMCOMMAND,	//tcm
	ECOMMAND_TCM_TIMEWIDTH,		//時間
	ECOMMAND_TCM_RESET,			//消しゴムボタン
	ECOMMAND_TCM_ALLRESET,		//白紙ボタン
	ECOMMAND_NUM,
};

enum eTCM_CLICK_STATE {
	ETCM_MOUSE_DOWN,
	ETCM_MOUSE_DOWN_BORDER,
	ETCM_MOUSE_DOWN_MOVE,
	ETCM_MOUSE_MOVE,
	ETCM_MOUSE_UP
};

enum eTCM_ANALYZ_STATE {
	ETCM_ANALYZ_NORMAL,
	ETCM_ANALYZ_WIDTH,
	ETCM_ANALYZ_WIDTH_LINE
};

#endif


